spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meter_db
    username: postgres
    password: mother1963
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    defaultSchema: my_custom_schema
